### ISSUE TITLE
Browsers won't allow autoplay

### ISSUE THREAD

**Issue by jamiesal** [paulirish/lite-youtube-embed#79] opened 2021-03-24 02:10 UTC
iOS devices and perhaps Safari on Macs won't begin playing the video after clicking on the thumbnail. Rather, the iframe replaces the img tag and the user must tap or click the play button a second time. This is not an ideal user experience. My assumption is that the browser is preventing injected iframe elements from autoplaying with sound turned on. Not sure if there is any way around this or if we should simply use "loading=lazy" on our youtube embeds instead of this program.

**Comment by kevinfarrugia** [comment] 2021-03-24 06:41
I think this duplicates #6 as the problem is on most mobile browsers.

**Comment by paulirish** [comment] 2022-09-11 01:54
dupe of #6

**Closed by paulirish** 2022-09-11 01:54 UTC
