### ISSUE TITLE
404 on default image

### ISSUE THREAD

**Issue by Onyemobi** [paulirish/lite-youtube-embed#45] opened 2019-12-23 15:11 UTC
After loading the code in my CRM, I get a 404 on the default image ( https://i.ytimg.com/vi/null/hqdefault.jpg ) despite it showing up on my screen. Furthermore, the Youtube embed does not play.

**Comment by paulirish** [comment] 2019-12-23 15:53
Can you share the videoid ?

**Comment by Onyemobi** [comment] 2019-12-23 15:55
87spd3KMs3U

**Comment by Onyemobi** [comment] 2019-12-23 15:56
<div class="new-embedded-video">
    <lite-youtube videoid="87spd3KMs3U">
        <div class="lty-playbtn"></div>
    </lite-youtube>
</div>

**Comment by lborgman** [comment] 2020-02-10 23:11
I use something like this. Not sure why anymore...

        async function getArturlImg(url) {
            if (!ytId) return undefined;
            async function checkImg(url) {
                const img = new Image();
                return new Promise((resolve, reject) => {
                    img.onload = function () {
                        // console.warn(`Found ${url}`);
                        resolve(img);
                    };
                    img.onerror = function () {
                        // console.error(`Did not find ${url}`);
                        resolve();
                    };
                    img.src = url;
                });
            }
            let imgUrls = [
                `https://img.youtube.com/vi_webp/${ytId}/maxresdefault.webp`,
                `https://img.youtube.com/vi/${ytId}/maxresdefault.jpg`,
                `https://img.youtube.com/vi/${ytId}/default.jpg`,
            ];
            if (url) { imgUrls.unshift(url); }
            for (let i = 0, len = imgUrls.length; i < len; i++) {
                const url = imgUrls[i];
                const img = await checkImg(url);
                if (img) {
                    if (img.naturalWidth === 120) {
                        if (i !== len - 1) {
                            // console.error(`Probably got YouTube fallback image, ${i}, ${len}: ${url}`);
                            continue;
                        }
                    }
                    return img;
                }

            }
        }

**Comment by Garbee** [comment] 2020-02-11 01:28
@Onyemobi Your default image URL has `null` where the ID should be. What CRM are you using and did you do any special integration module? Or is it just putting the direct HTML into a content block?

**Comment by rbardini** [comment] 2020-04-03 17:25
This also happened to me when I loaded the script before using the element. Deferring the script solved the problem.

**Comment by pinkiebala** [comment] 2020-04-23 06:54
I've run into the same situation when using lite-youtube with React.

According to [spec](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance):

> The element must not gain any attributes or children, as this violates the expectations of 
> consumers who use the createElement or createElementNS methods.
>
> In general, work should be deferred to connectedCallback as much as possible

Related issue: https://github.com/paulirish/lite-youtube-embed/issues/44
Happy to see that it may be fixed in #28

**Comment by web2033** [comment] 2020-05-12 13:22
I have the same issue with a statically generated site using Nuxt.js
It works on the first-page load, but after navigating to a different page and returning to a page with a video - https://i.ytimg.com/vi/null/hqdefault.jpg and no longer can play it.

I used the same videoid from Readme.

**Comment by Garbee** [comment] 2020-05-12 14:52
@web2033 Do you have a minimal sample case that reproduces the issue?

**Comment by web2033** [comment] 2020-05-12 15:52
> Do you have a minimal sample case that reproduces the issue?

@Garbee https://codesandbox.io/s/brave-pascal-cezu9

The first load works. Navigate to About Page and then back to Home and it doesn't work.

**Comment by paulirish** [comment] 2020-11-22 21:35
The majority of the above cases were fixed in https://github.com/paulirish/lite-youtube-embed/commit/0221be1727c6c338d8ae2e4cac5c8aa106ed5794  This is where you saw 	`null` in the image url.. it was because we used `getAttribute` before the element was available.   (the true issue was #44 ) 

The @lborgman comment is more about using the best thumbnail available, which i've opened a dedicated issue for: #70

**Closed by paulirish** 2020-11-22 21:35 UTC
