### ISSUE TITLE
I need two clicks to play video in Safari

### ISSUE THREAD

**Issue by zuzanasumlanskaSK** [paulirish/lite-youtube-embed#119] opened 2022-02-22 13:37 UTC
Hi, 

I have an issue with lite-youtube-embed. 

When I open this [link in Safari ](https://paulirish.github.io/lite-youtube-embed/)(version 15.3), I need two clicks to actually play the video. 

Is that a bug or it is supposed to work like that? In other browsers it's fine.

Thanks and have a nice day

**Comment by danielbachhuber** [comment] 2022-02-23 12:58
It looks like this is a duplicate of #6

**Comment by erikdemarco** [comment] 2022-03-26 06:27
This occurs not just in safari. Chrome and opera mobile needs 2click as well

**Comment by paulirish** [comment] 2022-09-11 01:54
dupe of #6

**Closed by paulirish** 2022-09-11 01:54 UTC
